// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB868GbTWXql1dH0pUrjOhym-7hRv9PV6s',
    appId: '1:1037012913702:web:fa9934eaf7f464a60160e7',
    messagingSenderId: '1037012913702',
    projectId: 'futuregate-2b24b',
    authDomain: 'futuregate-2b24b.firebaseapp.com',
    storageBucket: 'futuregate-2b24b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMwb0VoufSBKSe-h_REfH6ydb0A4SeJA0',
    appId: '1:1037012913702:android:42db8cf8d76bc7b10160e7',
    messagingSenderId: '1037012913702',
    projectId: 'futuregate-2b24b',
    storageBucket: 'futuregate-2b24b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPwu9GXM1EbGJP72CUk671nZkBZFhq5SQ',
    appId: '1:1037012913702:ios:39d99b5c756710020160e7',
    messagingSenderId: '1037012913702',
    projectId: 'futuregate-2b24b',
    storageBucket: 'futuregate-2b24b.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPwu9GXM1EbGJP72CUk671nZkBZFhq5SQ',
    appId: '1:1037012913702:ios:39d99b5c756710020160e7',
    messagingSenderId: '1037012913702',
    projectId: 'futuregate-2b24b',
    storageBucket: 'futuregate-2b24b.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB868GbTWXql1dH0pUrjOhym-7hRv9PV6s',
    appId: '1:1037012913702:web:e8cb0ec45f91703c0160e7',
    messagingSenderId: '1037012913702',
    projectId: 'futuregate-2b24b',
    authDomain: 'futuregate-2b24b.firebaseapp.com',
    storageBucket: 'futuregate-2b24b.firebasestorage.app',
  );
}
